// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3w2jyjIEkYbgh487gEYUuDr1trNT7JKo',
    appId: '1:1092033376029:web:d3917ee54eb2cb5b1a7bf4',
    messagingSenderId: '1092033376029',
    projectId: 'my-bank-app-02032024',
    authDomain: 'my-bank-app-02032024.firebaseapp.com',
    storageBucket: 'my-bank-app-02032024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiImeup1hjMdt-v1u5iEc8VGkBjlRx4C8',
    appId: '1:1092033376029:android:1bedaefdf65a78eb1a7bf4',
    messagingSenderId: '1092033376029',
    projectId: 'my-bank-app-02032024',
    storageBucket: 'my-bank-app-02032024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvqyBJVpI8Ll_pE65a2g2syfUiztL5gk',
    appId: '1:1092033376029:ios:57873f3a417478c51a7bf4',
    messagingSenderId: '1092033376029',
    projectId: 'my-bank-app-02032024',
    storageBucket: 'my-bank-app-02032024.appspot.com',
    iosBundleId: 'br.com.nickdev.bankApp',
  );
}
